config/routes.rb
Rails.application.routes.draw do
  resources :chats
  resources :todos
  root to: 'todos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[ show edit update destroy ]

  # GET /chats or /chats.json
  def index
    @chats = Chat.all
    @chat = Chat.new
    @incomeData ||= ""
    @new_message ||= ""
    # @pagy, @chats = pagy(Chat.all, page: 1, items: 1)
  end

  # GET /chats/1 or /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats or /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to chat_url(@chat), notice: "Chat was successfully created." }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to chat_url(@chat), notice: "Chat was successfully updated." }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to chats_url, notice: "Chat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat).permit(:message, :sender, :receiver)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
    @todo ||= Todo.new
    @todo ||= Todo.new
    @jet ||= ""
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:description, :completed_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/chats/_form.html.erb
<%= form_with(model: chat, local: true, data: { reflex: "submit->Message#create" }) do |form| %>
  <% if chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="field">
    <%= form.label :sender %>
    <%= form.text_field :sender %>
  </div>

  <div class="field">
    <%= form.label :receiver %>
    <%= form.text_field :receiver %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chats/_message_part.html.erb
<div id="new_sms">
    <b class="spa"><%= new_message["sender"] %> чамд <%= new_message["message"] %> явуулсан байна </b><br>
</div>

app/views/chats/_paginator.html.erb
<nav class="d-flex justify-content-center">
  <ul class="pagination">
    <li class="page-item"><a href="#" id="page_prev_li" class="page-link" data-reflex="click->Pagy#paginate" data-page="<%= pagy.prev || 1 %>"><span class="far fa-angle-double-left"></span></a></li>
    <% pagy.series.each do |item| %>
      <% if item == :gap %>
        <li class="page-item disabled"><a class="page-link" id="page_gap_li">...</a></li>
      <% else %>
        <li class="page-item <%= "active" if item.is_a?(String) %>">
          <a href="#" id="page_<%= item %>_li" class="page-link" data-reflex="click->Pagy#paginate" data-page="<%= item %>"><%= item %></a>
        </li>
      <% end %>
    <% end %>
    <li class="page-item"><a href="#" id="page_next_li" class="page-link" data-reflex="click->Pagy#paginate" data-page="<%= pagy.next || pagy.last %>"><span class="far fa-angle-double-right"></span></a></li>
  </ul>
</nav>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<p id="notice"><%= notice %></p>

  <%= render 'form', chat: @chat %>
  <%= render partial: 'message_part', locals: { new_message: @new_message } %>

  <div data-message-target="output"></div>


<b>Search</b>


    <table>
      <thead>
        <tr>
          <th>Message</th>
          <th>Sender</th>
          <th>Receiver</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @chats.each do |chat| %>
          <tr>
            <td><%= chat.message %></td>
            <td><%= chat.sender %></td>
            <td><%= chat.receiver %></td>
            <td><%= link_to 'Show', chat %></td>
            <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
            <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>



<h1>Chats</h1>


<br>

<%= link_to 'New Chat', new_chat_path %>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @chat.message %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @chat.sender %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @chat.receiver %>
</p>

<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimProducts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Home", root_path %>
    <%= link_to "chat", chats_path %>

    <%= yield %>
  </body>
</html>

app/views/todos/_foo.html.erb
<div id="foo">
    <p>foo is here ===></p>
    <b class="spa"><%= message %></b>
</div>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', data: { reflex: "change-> ExampleReflex#form" } %>
  </div>

  <div class="field">
    <%= form.label :completed_at %>
    <%= form.datetime_select :completed_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<header data-reflex="click->Example#change" >
  <p> === selector morphs === </p>
  <%= render partial: "foo", locals: { message: "Am I the Elixir or Rails?" } %>
</header>

<p id="notice"><%= notice %></p>

<h1>Todos</h1>
<%= render 'todos/form', todo: @todo %>
<p>=====================</p>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Description</th>
      <th>Completed at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <%= content_tag :tr, id: dom_id(todo), class: dom_class(todo) do %>
        <td><%= check_box_tag nil, nil, todo.completed_at? , data: {reflex: "click->ExampleReflex#toggle", id: todo.id} %></td>
        <td><%= todo.description %></td>
        <td><%= todo.completed_at %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

<h1>Counter to app/reflexes/counter_reflex.rb</h1>
<a href="#"
  data-reflex="click->Counter#increment"
  data-tamir="F22"
  data-step="1" 
  data-count="<%= @count.to_i %>"
>Air to air micro missiles (30mm) <%= @count.to_i %></a>

<h1> Fighter jet plane is <%= @jet %> </h1>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @todo.description %>
</p>

<p>
  <strong>Completed at:</strong>
  <%= @todo.completed_at %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>